FROM node:10.16.2-slim as dependencies

RUN mkdir /app
WORKDIR /app

COPY package.json .
ARG BATON_NODE_REST_API_SERVICE_HOST
ENV BATON_NODE_REST_API_SERVICE_HOST=${BATON_NODE_REST_API_SERVICE_HOST}

ARG BATON_NODE_REST_API_SERVICE_PORT
ENV BATON_NODE_REST_API_SERVICE_PORT=${BATON_NODE_REST_API_SERVICE_PORT}
RUN npm install



COPY . .

# Application port
EXPOSE 3000

CMD ["npm", "start"]



